import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar'
import { Button } from '@/components/ui/button'
import Link from 'next/link'
import { WithSidebar } from '@/components/ui/with-sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


const navBarPages = [
  {
    name: "My Books",
    href: "/my-books",
  },
  {
    name: "Activity",
    href: "/activity",
  },
]

const SidebarContent = () => {
  return (
    <div>
      <div>
        {/* todo add icons and link */}
        {/* todo add current page as active */}
        {navBarPages.map((item, index) => (
          <Link
            key={index}
            href={item.href}
            className="block rounded py-2.5 transition duration-200 hover:bg-green-300">
            {item.name}
          </Link>
        ))}
      </div>
    </div>
  )
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body className={inter.className}>
      <div className="border-b">
        <div className="flex h-16 items-center px-4 container mx-auto">
          Bookify
          <div className="ml-auto flex items-center space-x-4">
            <Avatar>
              <AvatarImage
                src="https://github.com/shadcn.png"
                alt="@shadcn"
              />
              <AvatarFallback>CN</AvatarFallback>
            </Avatar>
          </div>
        </div>
      </div>

      <div className="flex">
        <WithSidebar sidebarContent={SidebarContent} >

        <div className="w-full px-4 pt-8">{children}</div>
        </WithSidebar>
      </div>
    </body>
  </html>
  )
}
